{
 "title": "Throughput",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput por pessoa",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    assignee_name AS \"Assignee\", \r\n    COUNT(id) AS \"Issues\"\r\nFROM lake.issues\r\nWHERE resolution_date IS NOT NULL AND assignee_name != \"\"\r\nGROUP BY assignee_name\r\nORDER BY Issues DESC;\r\n"
    }
   ]
  },
  {
   "title": "Throughput por tipo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    original_type AS \"Tipo de issue\", \r\n    COUNT(id) AS Issues\r\nFROM lake.issues\r\nWHERE resolution_date IS NOT NULL AND original_type != \"\"\r\nGROUP BY original_type\r\nORDER BY Issues DESC;\r\n"
    }
   ]
  },
  {
   "title": "Throughput de issues por semana",
   "type": "trend",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    YEARWEEK(resolution_date, 1) AS week, \r\n    COUNT(id) AS Issues\r\nFROM lake.issues\r\nWHERE resolution_date IS NOT NULL\r\nGROUP BY week\r\nORDER BY week;\r\n"
    }
   ]
  },
  {
   "title": "Throughput de issues por mês",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "lake",
     "rawSql": "SELECT \r\n    UNIX_TIMESTAMP(DATE_FORMAT(resolution_date, '%Y-%m-01')) * 1000 AS time, \r\n    COUNT(id) AS issues_resolved\r\nFROM lake.issues\r\nWHERE resolution_date IS NOT NULL\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  }
 ]
}